quarkus.application.version=DUMMY_RELEASE
quarkus.log.console.format=[%d{HH:mm:ss}] %-5p > %s%e%n
quarkus.application.ui-header=Dockainer Launcher
quarkus.banner.enabled=false

dockainer.github.api.url=https://api.github.com/repos/dockainer/dockainer-launcher
dockainer.github.url=https://github.com/dockainer/dockainer-launcher